export const playerData = {
  player: [
    { id: "1643", name: "Aaron Finch", imageId: 244784, battingStyle: "Right-hand bat", bowlingStyle: "Left-arm orthodox", role: "Batsmen" },
    { id: "2250", name: "Steven Smith", imageId: 244808, battingStyle: "Right-hand bat", bowlingStyle: "Right-arm legbreak", role: "Batsmen" },
    { id: "1739", name: "David Warner", imageId: 244788, battingStyle: "Left-hand bat", bowlingStyle: "Right-arm legbreak", role: "Batsmen" },
    { id: "8121", name: "Joe Burns", imageId: 180293, battingStyle: "Right-hand bat", bowlingStyle: "Right-arm medium", role: "Batsmen" },
    { id: "12228", name: "Will Pucovski", imageId: 165716, battingStyle: "Right-hand bat", role: "Batsmen" },
    { id: "8497", name: "Travis Head", imageId: 147703, battingStyle: "Left-hand bat", bowlingStyle: "Right-arm offbreak", role: "Batsmen" },
    { id: "7662", name: "Glenn Maxwell", imageId: 244786, battingStyle: "Right-hand bat", bowlingStyle: "Right-arm offbreak", role: "All-Rounder" },
    { id: "8989", name: "Marcus Stoinis", imageId: 244801, battingStyle: "Right-hand bat", bowlingStyle: "Right-arm medium", role: "All-Rounder" },
    { id: "1437", name: "Moises Henriques", imageId: 152405, battingStyle: "Right-hand bat", bowlingStyle: "Right-arm fast-medium", role: "All-Rounder" },
    { id: "10182", name: "Marnus Labuschagne", imageId: 184115, battingStyle: "Right-hand bat", bowlingStyle: "Right-arm legbreak", role: "All-Rounder" },
    { id: "8130", name: "Michael Neser", imageId: 155994, battingStyle: "Right-hand bat", bowlingStyle: "Right-arm fast-medium", role: "All-Rounder" },
    { id: "8508", name: "Ashton Agar", imageId: 244781, battingStyle: "Left-hand bat", bowlingStyle: "Left-arm orthodox", role: "All-Rounder" },
    { id: "12225", name: "Cameron Green", imageId: 198706, battingStyle: "Right-hand bat", bowlingStyle: "Right-arm medium", role: "All-Rounder" },
    { id: "13162", name: "Daniel Sams", imageId: 180315, battingStyle: "Right-hand bat", bowlingStyle: "Left-arm fast-medium", role: "All-Rounder" },
    { id: "8136", name: "Sean Abbott", imageId: 191413, battingStyle: "Right-hand bat", bowlingStyle: "Right-arm medium", role: "All-Rounder" },
    { id: "9200", name: "Alex Carey", imageId: 170667, battingStyle: "Left-hand bat", role: "Wicket-Keeper" },
    { id: "1649", name: "Matthew Wade", imageId: 244799, battingStyle: "Left-hand bat", role: "Wicket-Keeper" },
    { id: "1994", name: "Tim Paine", imageId: 155979, battingStyle: "Right-hand bat", bowlingStyle: "Right-arm medium", role: "Wicket-Keeper" },
    { id: "8095", name: "Pat Cummins", imageId: 244803, battingStyle: "Right-hand bat", bowlingStyle: "Right-arm fast", role: "Bowler" },
    { id: "7850", name: "Nathan Lyon", imageId: 170650, battingStyle: "Right-hand bat", bowlingStyle: "Right-arm offbreak", role: "Bowler" },
    { id: "7710", name: "Mitchell Starc", imageId: 244806, battingStyle: "Left-hand bat", bowlingStyle: "Left-arm fast", role: "Bowler" },
    { id: "8642", name: "Adam Zampa", imageId: 244782, battingStyle: "Right-hand bat", bowlingStyle: "Right-arm legbreak", role: "Bowler" },
    { id: "6258", name: "Josh Hazlewood", imageId: 244790, battingStyle: "Left-hand bat", bowlingStyle: "Right-arm fast-medium", role: "Bowler" },
    { id: "9617", name: "Andrew Tye", imageId: 156051, battingStyle: "Right-hand bat", bowlingStyle: "Right-arm fast-medium", role: "Bowler" },
    { id: "2283", name: "James Pattinson", imageId: 151576, battingStyle: "Left-hand bat", bowlingStyle: "Right-arm fast", role: "Bowler" },
    { id: "624", name: "Eoin Morgan", imageId: 170936, battingStyle: "Left-hand bat", bowlingStyle: "Right-arm medium", role: "Batsmen" },
    { id: "8019", name: "Joe Root", imageId: 170942, battingStyle: "Right-hand bat", bowlingStyle: "Right-arm offbreak", role: "Batsmen" },
    { id: "6534", name: "Jason Roy", imageId: 170941, battingStyle: "Right-hand bat", role: "Batsmen" },
    { id: "10045", name: "Liam Livingstone", imageId: 244797, battingStyle: "Right-hand bat", bowlingStyle: "Right-arm legbreak", role: "Batsmen" },
    { id: "6660", name: "Dawid Malan", imageId: 244793, battingStyle: "Left-hand bat", bowlingStyle: "Right-arm legbreak", role: "Batsmen" },
    { id: "6692", name: "Moeen Ali", imageId: 244796, battingStyle: "Left-hand bat", bowlingStyle: "Right-arm offbreak", role: "All-Rounder" },
    { id: "6557", name: "Ben Stokes", imageId: 244791, battingStyle: "Left-hand bat", bowlingStyle: "Right-arm fast-medium", role: "All-Rounder" },
    { id: "6670", name: "Chris Woakes", imageId: 244787, battingStyle: "Right-hand bat", bowlingStyle: "Right-arm fast-medium", role: "All-Rounder" },
    { id: "9522", name: "Tom Curran", imageId: 170967, battingStyle: "Right-hand bat", bowlingStyle: "Right-arm fast-medium", role: "All-Rounder" },
    { id: "7854", name: "Lewis Gregory", imageId: 180929, battingStyle: "Right-hand bat", bowlingStyle: "Right-arm fast-medium", role: "All-Rounder" },
    { id: "10420", name: "Sam Curran", imageId: 244812, battingStyle: "Left-hand bat", bowlingStyle: "Left-arm fast-medium", role: "All-Rounder" },
    { id: "6507", name: "Jonny Bairstow", imageId: 170976, battingStyle: "Right-hand bat", bowlingStyle: "Right-arm medium", role: "Wicket-Keeper" },
    { id: "2258", name: "Jos Buttler", imageId: 244800, battingStyle: "Right-hand bat", role: "Wicket-Keeper" },
    { id: "7990", name: "Sam Billings", imageId: 156173, battingStyle: "Right-hand bat", role: "Wicket-Keeper" },
    { id: "1742", name: "Adil Rashid", imageId: 244789, battingStyle: "Right-hand bat", bowlingStyle: "Right-arm legbreak", role: "Bowler" },
    { id: "8383", name: "Mark Wood", imageId: 244802, battingStyle: "Right-hand bat", bowlingStyle: "Right-arm fast", role: "Bowler" },
    { id: "11540", name: "Jofra Archer", imageId: 170970, battingStyle: "Right-hand bat", bowlingStyle: "Right-arm fast", role: "Bowler" },
    { id: "8022", name: "Olly Stone", imageId: 156823, battingStyle: "Right-hand bat", bowlingStyle: "Right-arm fast", role: "Bowler" },
    { id: "8349", name: "Reece Topley", imageId: 244807, battingStyle: "Right-hand bat", bowlingStyle: "Left-arm fast-medium", role: "Bowler" },
    { id: "6532", name: "Chris Jordan", imageId: 244783, battingStyle: "Right-hand bat", bowlingStyle: "Right-arm fast-medium", role: "Bowler" },
  ],
};
